[package]
name = "rust_new"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
reqwest = "0.11.20"
tokio-stream = "0.1.14"
tokio = "1.32.0"
mini-redis = "0.4.1"
threadpool = "1.0"
